[connections.default]
    role = "SYSADMIN"
    account = "ACCOUNT-LOCATOR"
    user = "keypair_demo"
    database = "snowflake"
    authenticator = "SNOWFLAKE_JWT"
    private_key_file = ".snowflake/rsa_key.p8"