--!jinja
CREATE OR ALTER DATABASE BRONZE_{{ENV}}_db
DATA_RETENTION_TIME_IN_DAYS = 2
;
CREATE OR ALTER DATABASE SILVER_{{ENV}}_db
DATA_RETENTION_TIME_IN_DAYS = 1
;

CREATE OR ALTER DATABASE GOLD_{{ENV}}_db
DATA_RETENTION_TIME_IN_DAYS = 30
;