--Bronze
{% set DB = 'BRONZE'%}
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.ADT_FEEDS;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.CLAIMS_SYSTEM;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.REFERENCE;

--Silver
{% set DB = 'SILVER'%}
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.ADT_FEEDS;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.CLAIMS_SYSTEM;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.REFERENCE;

--Gold
{% set DB = 'GOLD'%}
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.MEMBERSHIP;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.CLAIMS;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.POPULATION_HEALTH;
CREATE OR REPLACE SCHEMA {{DB}}_{{ENV}}_DB.REFERENCE;

